name = "PackageRegistry"
uuid = "72dd8025-cb31-496f-8c7f-1c9bc4d661f1"
repo = "https://github.com/williamesamuelson/PackageRegistry.git"
description = "My private registry"

[packages]
312194fd-fec5-4b07-ba1c-a40d7013a56a = { name = "QuantumDots", path = "Q/QuantumDots" }
afc0e0ae-cd0a-41ee-b0f5-7950de095d62 = { name = "AffineRayleighOptimization", path = "A/AffineRayleighOptimization" }
