name = "PackageRegistry"
uuid = "72dd8025-cb31-496f-8c7f-1c9bc4d661f1"
repo = "https://github.com/williamesamuelson/PackageRegistry.git"
description = "My private registry"

[packages]
312194fd-fec5-4b07-ba1c-a40d7013a56a = { name = "QuantumDots", path = "Q/QuantumDots" }
82e5dd95-83c3-46b2-a303-acc930c81756 = { name = "FermionicHilbertSpaces", path = "F/FermionicHilbertSpaces" }
afc0e0ae-cd0a-41ee-b0f5-7950de095d62 = { name = "AffineRayleighOptimization", path = "A/AffineRayleighOptimization" }
c0bcf24a-0299-47db-9920-c7627388ccab = { name = "Majoranas", path = "M/Majoranas" }
